version: 1.0.34.{build}
image: Visual Studio 2019
before_build:
  - git submodule update -q --init --recursive
  - nuget restore -Verbosity quiet
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
build:
  project: eduVPN.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)\eduEd25519.dll
  - path: bin\$(configuration)\$(platform)\eduEd25519.pdb
  - path: bin\$(configuration)\$(platform)\ar\eduEd25519.resources.dll
  - path: bin\$(configuration)\$(platform)\de\eduEd25519.resources.dll
  - path: bin\$(configuration)\$(platform)\fr\eduEd25519.resources.dll
  - path: bin\$(configuration)\$(platform)\nl\eduEd25519.resources.dll
  - path: bin\$(configuration)\$(platform)\sl\eduEd25519.resources.dll
  - path: bin\$(configuration)\$(platform)\uk\eduEd25519.resources.dll
  - path: bin\$(configuration)\$(platform)\eduEx.dll
  - path: bin\$(configuration)\$(platform)\eduEx.pdb
  - path: bin\$(configuration)\$(platform)\eduJSON.dll
  - path: bin\$(configuration)\$(platform)\eduJSON.pdb
  - path: bin\$(configuration)\$(platform)\ar\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\de\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\fr\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\nl\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\sl\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\uk\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\eduOAuth.dll
  - path: bin\$(configuration)\$(platform)\eduOAuth.pdb
  - path: bin\$(configuration)\$(platform)\ar\eduOAuth.resources.dll
  - path: bin\$(configuration)\$(platform)\de\eduOAuth.resources.dll
  - path: bin\$(configuration)\$(platform)\fr\eduOAuth.resources.dll
  - path: bin\$(configuration)\$(platform)\nl\eduOAuth.resources.dll
  - path: bin\$(configuration)\$(platform)\sl\eduOAuth.resources.dll
  - path: bin\$(configuration)\$(platform)\uk\eduOAuth.resources.dll
  - path: bin\$(configuration)\$(platform)\eduOpenVPN.dll
  - path: bin\$(configuration)\$(platform)\eduOpenVPN.pdb
  - path: bin\$(configuration)\$(platform)\ar\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\de\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\fr\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\nl\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\sl\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\uk\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\eduVPN.dll
  - path: bin\$(configuration)\$(platform)\eduVPN.pdb
  - path: bin\$(configuration)\$(platform)\ar\eduVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\de\eduVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\fr\eduVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\nl\eduVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\sl\eduVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\uk\eduVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\eduVPN.Client.exe
  - path: bin\$(configuration)\$(platform)\eduVPN.Client.pdb
  - path: bin\$(configuration)\$(platform)\ar\eduVPN.Client.resources.dll
  - path: bin\$(configuration)\$(platform)\de\eduVPN.Client.resources.dll
  - path: bin\$(configuration)\$(platform)\fr\eduVPN.Client.resources.dll
  - path: bin\$(configuration)\$(platform)\nl\eduVPN.Client.resources.dll
  - path: bin\$(configuration)\$(platform)\sl\eduVPN.Client.resources.dll
  - path: bin\$(configuration)\$(platform)\uk\eduVPN.Client.resources.dll
  - path: bin\$(configuration)\$(platform)\eduVPN.Resources.dll
  - path: bin\$(configuration)\$(platform)\eduVPN.Resources.pdb
  - path: bin\$(configuration)\$(platform)\OpenVPN.Resources.dll
  - path: bin\$(configuration)\$(platform)\OpenVPN.Resources.pdb
