version: 4.0.1.{build}
image: Visual Studio 2022
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64

# Resort to own Git clone script to support submodules. Stock does not initialize submodules.
# Submodules must be initialized in the clone phase, as the cache phase - which requires submodules - is next in the pipeline.
# Reference: https://github.com/appveyor/ci/issues/899#issuecomment-567280434
clone_script:
  - ps: >-
      if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
        git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
        cd $env:APPVEYOR_BUILD_FOLDER
        git checkout -qf $env:APPVEYOR_REPO_COMMIT
      } else {
        git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
        cd $env:APPVEYOR_BUILD_FOLDER
        git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
        git checkout -qf FETCH_HEAD
      }
  - cmd: git submodule update --init --recursive
cache:
  - packages -> **\packages.config
  - eduMSICA\vcpkg_installed -> eduMSICA\eduMSICA.vcxproj, eduMSICA\vcpkg.json
  - openvpn\src\openvpn\vcpkg_installed -> openvpn\src\openvpn\openvpn.vcxproj, openvpn\src\openvpn\vcpkg.json
  - openvpn\src\openvpnmsica\vcpkg_installed -> openvpn\src\openvpnmsica\openvpnmsica.vcxproj, openvpn\src\openvpnmsica\openvpnmsica.props, openvpn\src\openvpnmsica\vcpkg.json
  - openvpn\src\openvpnserv\vcpkg_installed -> openvpn\src\openvpnserv\openvpnserv.vcxproj, openvpn\src\openvpnserv\vcpkg.json
  - wireguard-windows\.deps -> wireguard-windows\build.bat
before_build:
  - cmd: |
      if /i %platform% equ x86   "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64_x86   && nmake "BuildOpenVPN-%configuration%-%platform%" BuildWireGuard "BuildeduVPNCommon-%configuration%-%platform%" "BuildeduVPNWindows-%configuration%-%platform%" /ls
      if /i %platform% equ x64   "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64       && nmake "BuildOpenVPN-%configuration%-%platform%" BuildWireGuard "BuildeduVPNCommon-%configuration%-%platform%" "BuildeduVPNWindows-%configuration%-%platform%" /ls
      if /i %platform% equ ARM64 "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64_arm64 && nmake "BuildOpenVPN-%configuration%-%platform%" BuildWireGuard "BuildeduVPNCommon-%configuration%-%platform%" "BuildeduVPNWindows-%configuration%-%platform%" /ls
  - nuget restore -Verbosity quiet
build:
  project: eduVPN.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)
