version: 2.1.2.{build}
image: Visual Studio 2019
before_build:
  - git submodule update -q --init --recursive
  - nuget restore -Verbosity quiet
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
  - ARM64
build:
  project: eduVPN.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)
