//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eduVPN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eduVPN.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API server replied with an error..
        /// </summary>
        internal static string ErrorAPIServerReply {
            get {
                return ResourceManager.GetString("ErrorAPIServerReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate was disabled by an administrator..
        /// </summary>
        internal static string ErrorCertificateDisabled {
            get {
                return ResourceManager.GetString("ErrorCertificateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of client certificate failed..
        /// </summary>
        internal static string ErrorClientCertificateLoad {
            get {
                return ResourceManager.GetString("ErrorClientCertificateLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded file {0} is corrupt..
        /// </summary>
        internal static string ErrorDownloadedFileCorrupt {
            get {
                return ResourceManager.GetString("ErrorDownloadedFileCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading from web failed. Please check your internet connection..
        /// </summary>
        internal static string ErrorDownloading {
            get {
                return ResourceManager.GetString("ErrorDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading web resource signature failed..
        /// </summary>
        internal static string ErrorDownloadingSignature {
            get {
                return ResourceManager.GetString("ErrorDownloadingSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minisign public key with Id {0:X} already exists..
        /// </summary>
        internal static string ErrorDuplicateMinisignPublicKey {
            get {
                return ResourceManager.GetString("ErrorDuplicateMinisignPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of API endpoints failed..
        /// </summary>
        internal static string ErrorEndpointsLoad {
            get {
                return ResourceManager.GetString("ErrorEndpointsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP server redirected to an unsafe URI..
        /// </summary>
        internal static string ErrorHttpRedirectToUnsafeUri {
            get {
                return ResourceManager.GetString("ErrorHttpRedirectToUnsafeUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many HTTP redirects..
        /// </summary>
        internal static string ErrorHttpTooMayRedirects {
            get {
                return ResourceManager.GetString("ErrorHttpTooMayRedirects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer file not available. Updating aborted..
        /// </summary>
        internal static string ErrorInstallerFileUnavailable {
            get {
                return ResourceManager.GetString("ErrorInstallerFileUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Service failure..
        /// </summary>
        internal static string ErrorInteractiveService {
            get {
                return ResourceManager.GetString("ErrorInteractiveService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing the client to use {0} failed..
        /// </summary>
        internal static string ErrorInvalidAccessToken {
            get {
                return ResourceManager.GetString("ErrorInvalidAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hostname: hostnames contain letters, numbers, hyphens and dots..
        /// </summary>
        internal static string ErrorInvalidHostname {
            get {
                return ResourceManager.GetString("ErrorInvalidHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minisign public key is invalid..
        /// </summary>
        internal static string ErrorInvalidMinisignPublicKey {
            get {
                return ResourceManager.GetString("ErrorInvalidMinisignPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minisign signature is invalid..
        /// </summary>
        internal static string ErrorInvalidMinisignSignature {
            get {
                return ResourceManager.GetString("ErrorInvalidMinisignSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name {0} is not valid..
        /// </summary>
        internal static string ErrorInvalidPropertyName {
            get {
                return ResourceManager.GetString("ErrorInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying signature failed. Integrity of {0} is not valid..
        /// </summary>
        internal static string ErrorInvalidSignature {
            get {
                return ResourceManager.GetString("ErrorInvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of profile configuration failed..
        /// </summary>
        internal static string ErrorProfileConfigLoad {
            get {
                return ResourceManager.GetString("ErrorProfileConfigLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of the profile list failed..
        /// </summary>
        internal static string ErrorProfileListLoad {
            get {
                return ResourceManager.GetString("ErrorProfileListLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving of profile&apos;s OpenVPN configuration to &quot;{0}&quot; failed..
        /// </summary>
        internal static string ErrorSavingProfileConfiguration {
            get {
                return ResourceManager.GetString("ErrorSavingProfileConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting self-update failed..
        /// </summary>
        internal static string ErrorSelfUpdateDetection {
            get {
                return ResourceManager.GetString("ErrorSelfUpdateDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minisign public key is not supported..
        /// </summary>
        internal static string ErrorUnsupportedMinisignPublicKey {
            get {
                return ResourceManager.GetString("ErrorUnsupportedMinisignPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minisign signature is not supported..
        /// </summary>
        internal static string ErrorUnsupportedMinisignSignature {
            get {
                return ResourceManager.GetString("ErrorUnsupportedMinisignSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minisign public key is not trusted..
        /// </summary>
        internal static string ErrorUntrustedMinisignPublicKey {
            get {
                return ResourceManager.GetString("ErrorUntrustedMinisignPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading to web failed. Please check your internet connection..
        /// </summary>
        internal static string ErrorUploading {
            get {
                return ResourceManager.GetString("ErrorUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account was disabled by an administrator..
        /// </summary>
        internal static string ErrorUserDisabled {
            get {
                return ResourceManager.GetString("ErrorUserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding routes to system....
        /// </summary>
        internal static string OpenVPNStateTypeAddingRoutes {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeAddingRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning IP address to virtual network interface....
        /// </summary>
        internal static string OpenVPNStateTypeAssigningIP {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeAssigningIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating with server....
        /// </summary>
        internal static string OpenVPNStateTypeAuthenticating {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        internal static string OpenVPNStateTypeConnected {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string OpenVPNStateTypeConnecting {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A graceful exit is in progress....
        /// </summary>
        internal static string OpenVPNStateTypeExiting {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeExiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenVPN reported fatal error..
        /// </summary>
        internal static string OpenVPNStateTypeFatalError {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading configuration options from server....
        /// </summary>
        internal static string OpenVPNStateTypeGettingConfiguration {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeGettingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A restart has occurred....
        /// </summary>
        internal static string OpenVPNStateTypeReconnecting {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeReconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving server IP....
        /// </summary>
        internal static string OpenVPNStateTypeResolving {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeResolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to TCP server....
        /// </summary>
        internal static string OpenVPNStateTypeTcpConnecting {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeTcpConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for initial response from server....
        /// </summary>
        internal static string OpenVPNStateTypeWaiting {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeWaiting", resourceCulture);
            }
        }
    }
}
