//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eduVPN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eduVPN.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Institution&apos;s Country.
        /// </summary>
        internal static string AuthenticatingCountrySelectPageTitle2 {
            get {
                return ResourceManager.GetString("AuthenticatingCountrySelectPageTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Institution.
        /// </summary>
        internal static string AuthenticatingInstituteSelectPageTitle {
            get {
                return ResourceManager.GetString("AuthenticatingInstituteSelectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Profile.
        /// </summary>
        internal static string ConnectingProfileSelectPageTitle {
            get {
                return ResourceManager.GetString("ConnectingProfileSelectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL of your Provider.
        /// </summary>
        internal static string CustomInstancePageTitle {
            get {
                return ResourceManager.GetString("CustomInstancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API server replied with an error..
        /// </summary>
        internal static string ErrorAPIServerReply {
            get {
                return ResourceManager.GetString("ErrorAPIServerReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client authorization failed..
        /// </summary>
        internal static string ErrorAuthorization {
            get {
                return ResourceManager.GetString("ErrorAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate was disabled by an administrator..
        /// </summary>
        internal static string ErrorCertificateDisabled {
            get {
                return ResourceManager.GetString("ErrorCertificateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of client certificate failed..
        /// </summary>
        internal static string ErrorClientCertificateLoad {
            get {
                return ResourceManager.GetString("ErrorClientCertificateLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded file {0} is corrupt..
        /// </summary>
        internal static string ErrorDownloadedFileCorrupt {
            get {
                return ResourceManager.GetString("ErrorDownloadedFileCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading from web failed. Please check your internet connection..
        /// </summary>
        internal static string ErrorDownloading {
            get {
                return ResourceManager.GetString("ErrorDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading web resource signature failed..
        /// </summary>
        internal static string ErrorDownloadingSignature {
            get {
                return ResourceManager.GetString("ErrorDownloadingSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of API endpoints failed..
        /// </summary>
        internal static string ErrorEndpointsLoad {
            get {
                return ResourceManager.GetString("ErrorEndpointsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer file not available. Updating aborted..
        /// </summary>
        internal static string ErrorInstallerFileUnavailable {
            get {
                return ResourceManager.GetString("ErrorInstallerFileUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of the provider source {0} failed..
        /// </summary>
        internal static string ErrorInstanceSourceInfoLoad {
            get {
                return ResourceManager.GetString("ErrorInstanceSourceInfoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Service failure..
        /// </summary>
        internal static string ErrorInteractiveService {
            get {
                return ResourceManager.GetString("ErrorInteractiveService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hostname: hostnames contain letters, numbers, hyphens and dots..
        /// </summary>
        internal static string ErrorInvalidHostname {
            get {
                return ResourceManager.GetString("ErrorInvalidHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key is invalid or of unsupported format..
        /// </summary>
        internal static string ErrorInvalidPrivateKey {
            get {
                return ResourceManager.GetString("ErrorInvalidPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name {0} is not valid..
        /// </summary>
        internal static string ErrorInvalidPropertyName {
            get {
                return ResourceManager.GetString("ErrorInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying signature failed. Integrity of {0} is not valid..
        /// </summary>
        internal static string ErrorInvalidSignature {
            get {
                return ResourceManager.GetString("ErrorInvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TOTP response: it should contain exactly six (6) decimal numbers; no spaces or hyphens are allowed..
        /// </summary>
        internal static string ErrorInvalidTOTP {
            get {
                return ResourceManager.GetString("ErrorInvalidTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network interface with {0} ID not found..
        /// </summary>
        internal static string ErrorNetworkInterfaceIDNotFound {
            get {
                return ResourceManager.GetString("ErrorNetworkInterfaceIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network interface {0} not found..
        /// </summary>
        internal static string ErrorNetworkInterfaceNameNotFound {
            get {
                return ResourceManager.GetString("ErrorNetworkInterfaceNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access token granted..
        /// </summary>
        internal static string ErrorNullAccessToken {
            get {
                return ResourceManager.GetString("ErrorNullAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of profile configuration failed..
        /// </summary>
        internal static string ErrorProfileConfigLoad {
            get {
                return ResourceManager.GetString("ErrorProfileConfigLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of the profile list failed..
        /// </summary>
        internal static string ErrorProfileListLoad {
            get {
                return ResourceManager.GetString("ErrorProfileListLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving of profile&apos;s OpenVPN configuration to &quot;{0}&quot; failed..
        /// </summary>
        internal static string ErrorSavingProfileConfiguration {
            get {
                return ResourceManager.GetString("ErrorSavingProfileConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Factor Authentication enrollment failed..
        /// </summary>
        internal static string ErrorTwoFactorEnrollment {
            get {
                return ResourceManager.GetString("ErrorTwoFactorEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading to web failed. Please check your internet connection..
        /// </summary>
        internal static string ErrorUploading {
            get {
                return ResourceManager.GetString("ErrorUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account was disabled by an administrator..
        /// </summary>
        internal static string ErrorUserDisabled {
            get {
                return ResourceManager.GetString("ErrorUserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of user info failed..
        /// </summary>
        internal static string ErrorUserInfoLoad {
            get {
                return ResourceManager.GetString("ErrorUserInfoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string InitializingPageTitle {
            get {
                return ResourceManager.GetString("InitializingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget {0}.
        /// </summary>
        internal static string InstanceForget {
            get {
                return ResourceManager.GetString("InstanceForget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want to use the VPN?.
        /// </summary>
        internal static string InstanceSourceSelectPageTitle2 {
            get {
                return ResourceManager.GetString("InstanceSourceSelectPageTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Access.
        /// </summary>
        internal static string InstanceSourceTypeInstituteAccess {
            get {
                return ResourceManager.GetString("InstanceSourceTypeInstituteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Internet.
        /// </summary>
        internal static string InstanceSourceTypeSecureInternet {
            get {
                return ResourceManager.GetString("InstanceSourceTypeSecureInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Automatic&gt;.
        /// </summary>
        internal static string InterfaceNameAutomatic {
            get {
                return ResourceManager.GetString("InterfaceNameAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding routes to system....
        /// </summary>
        internal static string OpenVPNStateTypeAddingRoutes {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeAddingRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning IP address to virtual network interface....
        /// </summary>
        internal static string OpenVPNStateTypeAssigningIP {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeAssigningIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating with server....
        /// </summary>
        internal static string OpenVPNStateTypeAuthenticating {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        internal static string OpenVPNStateTypeConnected {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string OpenVPNStateTypeConnecting {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A graceful exit is in progress....
        /// </summary>
        internal static string OpenVPNStateTypeExiting {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeExiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenVPN reported fatal error..
        /// </summary>
        internal static string OpenVPNStateTypeFatalError {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading configuration options from server....
        /// </summary>
        internal static string OpenVPNStateTypeGettingConfiguration {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeGettingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A restart has occurred....
        /// </summary>
        internal static string OpenVPNStateTypeReconnecting {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeReconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving server IP....
        /// </summary>
        internal static string OpenVPNStateTypeResolving {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeResolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to TCP server....
        /// </summary>
        internal static string OpenVPNStateTypeTcpConnecting {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeTcpConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for initial response from server....
        /// </summary>
        internal static string OpenVPNStateTypeWaiting {
            get {
                return ResourceManager.GetString("OpenVPNStateTypeWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing update....
        /// </summary>
        internal static string SelfUpdatingPageTitle {
            get {
                return ResourceManager.GetString("SelfUpdatingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN Connection.
        /// </summary>
        internal static string StatusPageTitle {
            get {
                return ResourceManager.GetString("StatusPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time-based One-Time Password (TOTP).
        /// </summary>
        internal static string TwoFactorAuthenticationMethodTOTP {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationMethodTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YubiKey.
        /// </summary>
        internal static string TwoFactorAuthenticationMethodYubiKey {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationMethodYubiKey", resourceCulture);
            }
        }
    }
}
