//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eduVPN.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// The last product version user was prompted to update to
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The last product version user was prompted to update to")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelfUpdateLastVersion {
            get {
                return ((string)(this["SelfUpdateLastVersion"]));
            }
            set {
                this["SelfUpdateLastVersion"] = value;
            }
        }
        
        /// <summary>
        /// The last time user was prompted to update at
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The last time user was prompted to update at")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime SelfUpdateLastReminder {
            get {
                return ((global::System.DateTime)(this["SelfUpdateLastReminder"]));
            }
            set {
                this["SelfUpdateLastReminder"] = value;
            }
        }
        
        /// <summary>
        /// Which OpenVPN interactive service instance client should use to manipulate openvpn.exe process:
        /// - &quot;$eduVPN&quot; - Use OpenVPN installation bundled with the client.
        /// - &quot;&quot; - Use original OpenVPN installation.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Which OpenVPN interactive service instance client should use to manipulate openvp" +
            "n.exe process:\r\n - \"$eduVPN\" - Use OpenVPN installation bundled with the client." +
            "\r\n - \"\" - Use original OpenVPN installation.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenVPNInteractiveServiceInstance {
            get {
                return ((string)(this["OpenVPNInteractiveServiceInstance"]));
            }
        }
        
        /// <summary>
        /// Always connect using TCP.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Always connect using TCP.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenVPNForceTCP {
            get {
                return ((bool)(this["OpenVPNForceTCP"]));
            }
            set {
                this["OpenVPNForceTCP"] = value;
            }
        }
        
        /// <summary>
        /// A flag to trigger setting upgrade from the previous version
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("A flag to trigger setting upgrade from the previous version")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingsVersion {
            get {
                return ((int)(this["SettingsVersion"]));
            }
            set {
                this["SettingsVersion"] = value;
            }
        }
        
        /// <summary>
        /// Options to be removed from OpenVPN profile configuration (when provisioned). List OpenVPN option names only - i.e. without parameters. Use in combination with OpenVPNAddOptions setting to override the OpenVPN options provisioned by the VPN provider.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Options to be removed from OpenVPN profile configuration (when provisioned). List" +
            " OpenVPN option names only - i.e. without parameters. Use in combination with Op" +
            "enVPNAddOptions setting to override the OpenVPN options provisioned by the VPN p" +
            "rovider.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OpenVPNRemoveOptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OpenVPNRemoveOptions"]));
            }
        }
        
        /// <summary>
        /// Custom options to be added to OpenVPN profile configuration. This string is appended to the OpenVPN profile configuration file (OVPN) and should conform to the OVPN file syntax. It can contain multiple lines to specify multiple OpenVPN options. Use in combination with OpenVPNRemoveOptions setting to override the OpenVPN options provisioned by the VPN provider.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute(@"Custom options to be added to OpenVPN profile configuration. This string is appended to the OpenVPN profile configuration file (OVPN) and should conform to the OVPN file syntax. It can contain multiple lines to specify multiple OpenVPN options. Use in combination with OpenVPNRemoveOptions setting to override the OpenVPN options provisioned by the VPN provider.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenVPNAddOptions {
            get {
                return ((string)(this["OpenVPNAddOptions"]));
            }
        }
        
        /// <summary>
        /// Profile to automatically connect to on startup
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Profile to automatically connect to on startup")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::eduVPN.Xml.StartSessionParams AutoStartProfile {
            get {
                return ((global::eduVPN.Xml.StartSessionParams)(this["AutoStartProfile"]));
            }
            set {
                this["AutoStartProfile"] = value;
            }
        }
        
        /// <summary>
        /// User&apos;s home organization for secure internet use
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("User\'s home organization for secure internet use")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecureInternetOrganization {
            get {
                return ((string)(this["SecureInternetOrganization"]));
            }
            set {
                this["SecureInternetOrganization"] = value;
            }
        }
        
        /// <summary>
        /// Last connecting server for secure internet use
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Last connecting server for secure internet use")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Uri SecureInternetConnectingServer {
            get {
                return ((global::System.Uri)(this["SecureInternetConnectingServer"]));
            }
            set {
                this["SecureInternetConnectingServer"] = value;
            }
        }
        
        /// <summary>
        /// List of institute access servers user connects to
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("List of institute access servers user connects to")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<UriList/>")]
        public global::eduVPN.Xml.UriList InstituteAccessServers {
            get {
                return ((global::eduVPN.Xml.UriList)(this["InstituteAccessServers"]));
            }
            set {
                this["InstituteAccessServers"] = value;
            }
        }
        
        /// <summary>
        /// List of own servers user connects to
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("List of own servers user connects to")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<UriList/>")]
        public global::eduVPN.Xml.UriList OwnServers {
            get {
                return ((global::eduVPN.Xml.UriList)(this["OwnServers"]));
            }
            set {
                this["OwnServers"] = value;
            }
        }
        
        /// <summary>
        /// Server list discovery URI
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Server list discovery URI")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::eduVPN.Xml.ResourceRef ServersDiscovery {
            get {
                return ((global::eduVPN.Xml.ResourceRef)(this["ServersDiscovery"]));
            }
        }
        
        /// <summary>
        /// Organization list discovery URI
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Organization list discovery URI")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::eduVPN.Xml.ResourceRef OrganizationsDiscovery {
            get {
                return ((global::eduVPN.Xml.ResourceRef)(this["OrganizationsDiscovery"]));
            }
        }
        
        /// <summary>
        /// Self-updating feature base URI
        /// Set to empty to disable self-updating.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Self-updating feature base URI\r\n Set to empty to disable self-updating.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::eduVPN.Xml.ResourceRef SelfUpdateDiscovery {
            get {
                return ((global::eduVPN.Xml.ResourceRef)(this["SelfUpdateDiscovery"]));
            }
        }
        
        /// <summary>
        /// Cache of sequenced JSON responses
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cache of sequenced JSON responses")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<JSONResponseDictionary/>")]
        public global::eduVPN.Xml.JSONResponseDictionary ResponseCache {
            get {
                return ((global::eduVPN.Xml.JSONResponseDictionary)(this["ResponseCache"]));
            }
            set {
                this["ResponseCache"] = value;
            }
        }
        
        /// <summary>
        /// Access token cache
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Access token cache")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AccessTokenDictionary/>")]
        public global::eduVPN.Xml.AccessTokenDictionary AccessTokenCache {
            get {
                return ((global::eduVPN.Xml.AccessTokenDictionary)(this["AccessTokenCache"]));
            }
            set {
                this["AccessTokenCache"] = value;
            }
        }
        
        /// <summary>
        /// Which profile of the server user selected last
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Which profile of the server user selected last")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<SerializableStringDictionary/>")]
        public global::eduVPN.Xml.SerializableStringDictionary LastSelectedProfile {
            get {
                return ((global::eduVPN.Xml.SerializableStringDictionary)(this["LastSelectedProfile"]));
            }
            set {
                this["LastSelectedProfile"] = value;
            }
        }
    }
}
