//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resources.rc
#define IDS_EDUVPN_MGR_SERVICE_TITLE            1
#define IDS_EDUVPN_MGR_SERVICE_DESCRIPTION      2
#define IDS_EDUVPN_TUN_SERVICE_TITLE            3
#define IDS_EDUVPN_TUN_SERVICE_DESCRIPTION      4

#define IDS_LETSCONNECT_MGR_SERVICE_TITLE       101
#define IDS_LETSCONNECT_MGR_SERVICE_DESCRIPTION 102
#define IDS_LETSCONNECT_TUN_SERVICE_TITLE       103
#define IDS_LETSCONNECT_TUN_SERVICE_DESCRIPTION 104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
