//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eduVPN.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eduVPN.Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your institution&apos;s country here. You can select VPN endpoints in other countries after signing in with your institution credentials..
        /// </summary>
        public static string AuthenticatingCountrySelectPageDescription {
            get {
                return ResourceManager.GetString("AuthenticatingCountrySelectPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Country.
        /// </summary>
        public static string AuthenticatingCountrySelectPageTitle {
            get {
                return ResourceManager.GetString("AuthenticatingCountrySelectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Institution.
        /// </summary>
        public static string AuthenticatingInstituteSelectPageTitle {
            get {
                return ResourceManager.GetString("AuthenticatingInstituteSelectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eduVPN client needs {0} authorization, and has opened an authorization web page in your browser.
        ///The client will continue after you complete the authorization....
        /// </summary>
        public static string AuthorizationPopupMessage {
            get {
                return ResourceManager.GetString("AuthorizationPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string AuthorizationPopupRetry {
            get {
                return ResourceManager.GetString("AuthorizationPopupRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for authorization.
        /// </summary>
        public static string AuthorizationPopupTitle {
            get {
                return ResourceManager.GetString("AuthorizationPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBackTitle {
            get {
                return ResourceManager.GetString("ButtonBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonCloseTitle {
            get {
                return ResourceManager.GetString("ButtonCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNextTitle {
            get {
                return ResourceManager.GetString("ButtonNextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectingProfileSelectPageTitle {
            get {
                return ResourceManager.GetString("ConnectingProfileSelectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter hostname of your VPN provider..
        /// </summary>
        public static string CustomInstancePageDescription {
            get {
                return ResourceManager.GetString("CustomInstancePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other address.
        /// </summary>
        public static string CustomInstancePageTitle {
            get {
                return ResourceManager.GetString("CustomInstancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string InitializingPageTitle {
            get {
                return ResourceManager.GetString("InitializingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add other address.
        /// </summary>
        public static string InstanceSourceSelectCustom {
            get {
                return ResourceManager.GetString("InstanceSourceSelectCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the profile type you want to use below. You will be redirected to the browser for your credentials..
        /// </summary>
        public static string InstanceSourceSelectPageDescription {
            get {
                return ResourceManager.GetString("InstanceSourceSelectPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your profile.
        /// </summary>
        public static string InstanceSourceSelectPageTitle {
            get {
                return ResourceManager.GetString("InstanceSourceSelectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your institute&apos;s network from outside the institution..
        /// </summary>
        public static string InstituteAccessNote {
            get {
                return ResourceManager.GetString("InstituteAccessNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Access.
        /// </summary>
        public static string InstituteAccessTitle {
            get {
                return ResourceManager.GetString("InstituteAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        public static string ListBoxNoItems {
            get {
                return ResourceManager.GetString("ListBoxNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eduVPN.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string MessageMaintenanceBegin {
            get {
                return ResourceManager.GetString("MessageMaintenanceBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string MessageMaintenanceEnd {
            get {
                return ResourceManager.GetString("MessageMaintenanceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance notification.
        /// </summary>
        public static string MessageMaintenanceTitle {
            get {
                return ResourceManager.GetString("MessageMaintenanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string MessageNotificationTitle {
            get {
                return ResourceManager.GetString("MessageNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G}{1}{2}.
        /// </summary>
        public static string NumberToHumanReadable {
            get {
                return ResourceManager.GetString("NumberToHumanReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another profile.
        /// </summary>
        public static string RecentConfigurationSelectPageAddProfile {
            get {
                return ResourceManager.GetString("RecentConfigurationSelectPageAddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to the internet securely, for example when using public WiFi..
        /// </summary>
        public static string SecureInternetNote {
            get {
                return ResourceManager.GetString("SecureInternetNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Internet.
        /// </summary>
        public static string SecureInternetTitle {
            get {
                return ResourceManager.GetString("SecureInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string StatusPageDisconnect {
            get {
                return ResourceManager.GetString("StatusPageDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string StatusPageInstance {
            get {
                return ResourceManager.GetString("StatusPageInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string StatusPageProfile {
            get {
                return ResourceManager.GetString("StatusPageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes in.
        /// </summary>
        public static string StatusPageSessionInfoBytesIn {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoBytesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes out.
        /// </summary>
        public static string StatusPageSessionInfoBytesOut {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoBytesOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string StatusPageSessionInfoDuration {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4.
        /// </summary>
        public static string StatusPageSessionInfoIPv4 {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoIPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6.
        /// </summary>
        public static string StatusPageSessionInfoIPv6 {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoIPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection info.
        /// </summary>
        public static string StatusPageSessionInfoTitle {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View log.
        /// </summary>
        public static string StatusPageSessionInfoViewLog {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusPageStatus {
            get {
                return ResourceManager.GetString("StatusPageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN connection.
        /// </summary>
        public static string StatusPageTitle {
            get {
                return ResourceManager.GetString("StatusPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string SystemTrayMenuExit {
            get {
                return ResourceManager.GetString("SystemTrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection _info....
        /// </summary>
        public static string SystemTrayMenuStatus {
            get {
                return ResourceManager.GetString("SystemTrayMenuStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h\:mm\:ss.
        /// </summary>
        public static string TimeSpanInSeconds {
            get {
                return ResourceManager.GetString("TimeSpanInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d\.hh\:mm\:ss.
        /// </summary>
        public static string TimeSpanInSecondsWithDays {
            get {
                return ResourceManager.GetString("TimeSpanInSecondsWithDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires two-factor authentication.
        /// </summary>
        public static string TwoFactorAuthenticationRequired {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Your account is marked as disabled. You might not be able to connect. Please, contact your helpdesk for support..
        /// </summary>
        public static string UserDisabledMessage {
            get {
                return ResourceManager.GetString("UserDisabledMessage", resourceCulture);
            }
        }
    }
}
