//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eduVPN.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eduVPN.Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2017
        ///The Commons Conservancy eduVPN Programme.
        /// </summary>
        public static string AboutPageCopyright {
            get {
                return ResourceManager.GetString("AboutPageCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eduVPN
        ///Powered by SURFnet.
        /// </summary>
        public static string AboutPageeduVPN {
            get {
                return ResourceManager.GetString("AboutPageeduVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutPageVersion {
            get {
                return ResourceManager.GetString("AboutPageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Country.
        /// </summary>
        public static string AuthenticatingCountrySelectPageTitle {
            get {
                return ResourceManager.GetString("AuthenticatingCountrySelectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Institution.
        /// </summary>
        public static string AuthenticatingInstituteSelectPageTitle {
            get {
                return ResourceManager.GetString("AuthenticatingInstituteSelectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VPN client needs {0} authorization, and has opened your web browser. The client will continue after you complete the authorization....
        /// </summary>
        public static string AuthorizationPopupMessage {
            get {
                return ResourceManager.GetString("AuthorizationPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting For Authorization.
        /// </summary>
        public static string AuthorizationPopupTitle {
            get {
                return ResourceManager.GetString("AuthorizationPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBackTitle {
            get {
                return ResourceManager.GetString("ButtonBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonCloseTitle {
            get {
                return ResourceManager.GetString("ButtonCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string ButtonNextTitle {
            get {
                return ResourceManager.GetString("ButtonNextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOKTitle {
            get {
                return ResourceManager.GetString("ButtonOKTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ButtonSettingsTitle {
            get {
                return ResourceManager.GetString("ButtonSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectingProfileSelectPageTitle {
            get {
                return ResourceManager.GetString("ConnectingProfileSelectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter hostname of your VPN provider..
        /// </summary>
        public static string CustomInstancePageDescription {
            get {
                return ResourceManager.GetString("CustomInstancePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Address.
        /// </summary>
        public static string CustomInstancePageTitle {
            get {
                return ResourceManager.GetString("CustomInstancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required OAuth parameter &quot;state&quot; is missing or incorrect..
        /// </summary>
        public static string ErrorOAuthState {
            get {
                return ResourceManager.GetString("ErrorOAuthState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string InitializingPageTitle {
            get {
                return ResourceManager.GetString("InitializingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add other address.
        /// </summary>
        public static string InstanceSourceSelectCustom {
            get {
                return ResourceManager.GetString("InstanceSourceSelectCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the VPN types below..
        /// </summary>
        public static string InstanceSourceSelectPageDescription {
            get {
                return ResourceManager.GetString("InstanceSourceSelectPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select VPN Type.
        /// </summary>
        public static string InstanceSourceSelectPageTitle {
            get {
                return ResourceManager.GetString("InstanceSourceSelectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your institute&apos;s network..
        /// </summary>
        public static string InstituteAccessNote {
            get {
                return ResourceManager.GetString("InstituteAccessNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Access.
        /// </summary>
        public static string InstituteAccessTitle {
            get {
                return ResourceManager.GetString("InstituteAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        public static string ListBoxNoItems {
            get {
                return ResourceManager.GetString("ListBoxNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string ListBoxNull {
            get {
                return ResourceManager.GetString("ListBoxNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eduVPN.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string MessageMaintenanceBegin {
            get {
                return ResourceManager.GetString("MessageMaintenanceBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string MessageMaintenanceEnd {
            get {
                return ResourceManager.GetString("MessageMaintenanceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Notification.
        /// </summary>
        public static string MessageMaintenanceTitle {
            get {
                return ResourceManager.GetString("MessageMaintenanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string MessageNotificationTitle {
            get {
                return ResourceManager.GetString("MessageNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G}{1}{2}.
        /// </summary>
        public static string NumberToHumanReadable {
            get {
                return ResourceManager.GetString("NumberToHumanReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password for &quot;{0}&quot;:.
        /// </summary>
        public static string PasswordPopupMessage {
            get {
                return ResourceManager.GetString("PasswordPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPopupPasswordTitle {
            get {
                return ResourceManager.GetString("PasswordPopupPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPopupTitle {
            get {
                return ResourceManager.GetString("PasswordPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another provider.
        /// </summary>
        public static string RecentConfigurationSelectPageAddEntry {
            get {
                return ResourceManager.GetString("RecentConfigurationSelectPageAddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to the Internet securely, for example when using public WiFi..
        /// </summary>
        public static string SecureInternetNote {
            get {
                return ResourceManager.GetString("SecureInternetNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Internet.
        /// </summary>
        public static string SecureInternetTitle {
            get {
                return ResourceManager.GetString("SecureInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask me later.
        /// </summary>
        public static string SelfUpdatePopupAskLater {
            get {
                return ResourceManager.GetString("SelfUpdatePopupAskLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New?.
        /// </summary>
        public static string SelfUpdatePopupChangelog {
            get {
                return ResourceManager.GetString("SelfUpdatePopupChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} of VPN client is installed. A newer version {1} is is available online..
        /// </summary>
        public static string SelfUpdatePopupMessage3 {
            get {
                return ResourceManager.GetString("SelfUpdatePopupMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        public static string SelfUpdatePopupSkip {
            get {
                return ResourceManager.GetString("SelfUpdatePopupSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string SelfUpdatePopupTitle {
            get {
                return ResourceManager.GetString("SelfUpdatePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and update now
        ///(Client will restart).
        /// </summary>
        public static string SelfUpdatePopupUpdate4 {
            get {
                return ResourceManager.GetString("SelfUpdatePopupUpdate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing update....
        /// </summary>
        public static string SelfUpdatingPageTitle {
            get {
                return ResourceManager.GetString("SelfUpdatingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has detected that your user settings file {1} has become corrupted. This may be due to a crash.
        ///
        ///If you continue, your user settings will be reset to the default..
        /// </summary>
        public static string SettingsCorruptErrorMessage {
            get {
                return ResourceManager.GetString("SettingsCorruptErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt User Settings.
        /// </summary>
        public static string SettingsCorruptErrorTitle {
            get {
                return ResourceManager.GetString("SettingsCorruptErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the VPN client cannot connect, or can connect but doesn&apos;t transfer data, connecting over TCP could solve this..
        /// </summary>
        public static string SettingsPageForceTCPDescription {
            get {
                return ResourceManager.GetString("SettingsPageForceTCPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Over TCP.
        /// </summary>
        public static string SettingsPageForceTCPInterfaceTitle {
            get {
                return ResourceManager.GetString("SettingsPageForceTCPInterfaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you need multiple simultaneous OpenVPN connections, select the TAP interface for this VPN client below..
        /// </summary>
        public static string SettingsPageInterfaceDescription {
            get {
                return ResourceManager.GetString("SettingsPageInterfaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TAP Interface.
        /// </summary>
        public static string SettingsPageInterfaceTitle {
            get {
                return ResourceManager.GetString("SettingsPageInterfaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string StatusPageDisconnect {
            get {
                return ResourceManager.GetString("StatusPageDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string StatusPageInstance {
            get {
                return ResourceManager.GetString("StatusPageInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string StatusPageProfile {
            get {
                return ResourceManager.GetString("StatusPageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes In.
        /// </summary>
        public static string StatusPageSessionInfoBytesIn {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoBytesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes Out.
        /// </summary>
        public static string StatusPageSessionInfoBytesOut {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoBytesOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string StatusPageSessionInfoDuration {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4.
        /// </summary>
        public static string StatusPageSessionInfoIPv4 {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoIPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6.
        /// </summary>
        public static string StatusPageSessionInfoIPv6 {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoIPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Info.
        /// </summary>
        public static string StatusPageSessionInfoTitle {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View log.
        /// </summary>
        public static string StatusPageSessionInfoViewLog {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusPageStatus {
            get {
                return ResourceManager.GetString("StatusPageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN Connection.
        /// </summary>
        public static string StatusPageTitle {
            get {
                return ResourceManager.GetString("StatusPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP={0}, IPv6={1}.
        /// </summary>
        public static string SystemTrayBalloonConnectedMessage {
            get {
                return ResourceManager.GetString("SystemTrayBalloonConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Connected.
        /// </summary>
        public static string SystemTrayBalloonConnectedTitle {
            get {
                return ResourceManager.GetString("SystemTrayBalloonConnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window has been minimized here..
        /// </summary>
        public static string SystemTrayBalloonHiddenMessage {
            get {
                return ResourceManager.GetString("SystemTrayBalloonHiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string SystemTrayMenuAbout {
            get {
                return ResourceManager.GetString("SystemTrayMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string SystemTrayMenuExit {
            get {
                return ResourceManager.GetString("SystemTrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string SystemTrayMenuOpen {
            get {
                return ResourceManager.GetString("SystemTrayMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings....
        /// </summary>
        public static string SystemTrayMenuSettings {
            get {
                return ResourceManager.GetString("SystemTrayMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection _info....
        /// </summary>
        public static string SystemTrayMenuStatus {
            get {
                return ResourceManager.GetString("SystemTrayMenuStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h\:mm\:ss.
        /// </summary>
        public static string TimeSpanInSeconds {
            get {
                return ResourceManager.GetString("TimeSpanInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d\.hh\:mm\:ss.
        /// </summary>
        public static string TimeSpanInSecondsWithDays {
            get {
                return ResourceManager.GetString("TimeSpanInSecondsWithDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not reuse the TOTP. Wait until a fresh TOTP is generated..
        /// </summary>
        public static string TOTPAuthenticationNote {
            get {
                return ResourceManager.GetString("TOTPAuthenticationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string TOTPEnrollmentPanelResponseTitle {
            get {
                return ResourceManager.GetString("TOTPEnrollmentPanelResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        public static string TOTPEnrollmentPanelSecretTitle {
            get {
                return ResourceManager.GetString("TOTPEnrollmentPanelSecretTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your two-factor method and enter the security token:.
        /// </summary>
        public static string TwoFactorAuthenticationPopupMessage {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor Authentication.
        /// </summary>
        public static string TwoFactorAuthenticationPopupTitle {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires two-factor authentication.
        /// </summary>
        public static string TwoFactorAuthenticationRequired {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll.
        /// </summary>
        public static string TwoFactorEnrollmentButton {
            get {
                return ResourceManager.GetString("TwoFactorEnrollmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires you to enroll for two-factor authentication at {1}..
        /// </summary>
        public static string TwoFactorEnrollmentPopupMessage {
            get {
                return ResourceManager.GetString("TwoFactorEnrollmentPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor Authentication Enrollment.
        /// </summary>
        public static string TwoFactorEnrollmentPopupTitle {
            get {
                return ResourceManager.GetString("TwoFactorEnrollmentPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Your account is disabled. Please, contact your helpdesk for support..
        /// </summary>
        public static string UserDisabledMessage {
            get {
                return ResourceManager.GetString("UserDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and password for &quot;{0}&quot;:.
        /// </summary>
        public static string UsernamePasswordPopupMessage {
            get {
                return ResourceManager.GetString("UsernamePasswordPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UsernamePasswordPopupPasswordTitle {
            get {
                return ResourceManager.GetString("UsernamePasswordPopupPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string UsernamePasswordPopupTitle {
            get {
                return ResourceManager.GetString("UsernamePasswordPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernamePasswordPopupUsernameTitle {
            get {
                return ResourceManager.GetString("UsernamePasswordPopupUsernameTitle", resourceCulture);
            }
        }
    }
}
