//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eduVPN.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eduVPN.Views.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog....
        /// </summary>
        public static string AboutPageChangelogTitle {
            get {
                return ResourceManager.GetString("AboutPageChangelogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download {0} and _update now
        ///(Client will restart).
        /// </summary>
        public static string AboutPageUpdateTitle {
            get {
                return ResourceManager.GetString("AboutPageUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutPageVersion {
            get {
                return ResourceManager.GetString("AboutPageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More _info.
        /// </summary>
        public static string AuthorizationPageMoreInfoLabel {
            get {
                return ResourceManager.GetString("AuthorizationPageMoreInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your browser did not open for some reason, or you closed the website by accident, here is the URL you may copy&amp;paste into a trusted browser on this computer, and complete the client authorization there:.
        /// </summary>
        public static string AuthorizationPageNote {
            get {
                return ResourceManager.GetString("AuthorizationPageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app needs authorization and has opened your webbrowser. It will proceed when you have completed the authorization..
        /// </summary>
        public static string AuthorizationPageText {
            get {
                return ResourceManager.GetString("AuthorizationPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization required.
        /// </summary>
        public static string AuthorizationPageTitle {
            get {
                return ResourceManager.GetString("AuthorizationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_bout.
        /// </summary>
        public static string ButtonAboutTitle {
            get {
                return ResourceManager.GetString("ButtonAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBackTitle {
            get {
                return ResourceManager.GetString("ButtonBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancelTitle {
            get {
                return ResourceManager.GetString("ButtonCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Error Text.
        /// </summary>
        public static string ButtonCopyErrorTitle {
            get {
                return ResourceManager.GetString("ButtonCopyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy URI.
        /// </summary>
        public static string ButtonCopyUriTitle {
            get {
                return ResourceManager.GetString("ButtonCopyUriTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dismiss Error.
        /// </summary>
        public static string ButtonDismissErrorTitle {
            get {
                return ResourceManager.GetString("ButtonDismissErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string ButtonSettingsTitle {
            get {
                return ResourceManager.GetString("ButtonSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ConnectionPageConnectionInfo {
            get {
                return ResourceManager.GetString("ConnectionPageConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded:.
        /// </summary>
        public static string ConnectionPageConnectionInfoBytesIn2 {
            get {
                return ResourceManager.GetString("ConnectionPageConnectionInfoBytesIn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded:.
        /// </summary>
        public static string ConnectionPageConnectionInfoBytesOut2 {
            get {
                return ResourceManager.GetString("ConnectionPageConnectionInfoBytesOut2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Transferred.
        /// </summary>
        public static string ConnectionPageConnectionInfoDataTransferred {
            get {
                return ResourceManager.GetString("ConnectionPageConnectionInfoDataTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection _info.
        /// </summary>
        public static string ConnectionPageConnectionInfoLabel {
            get {
                return ResourceManager.GetString("ConnectionPageConnectionInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ConnectionPageConnectionInfoProfile {
            get {
                return ResourceManager.GetString("ConnectionPageConnectionInfoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid for.
        /// </summary>
        public static string ConnectionPageConnectionInfoValidFor {
            get {
                return ResourceManager.GetString("ConnectionPageConnectionInfoValidFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid for.
        /// </summary>
        public static string ConnectionPageOAuthValidLabel {
            get {
                return ResourceManager.GetString("ConnectionPageOAuthValidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no profiles available to connect..
        /// </summary>
        public static string ConnectionPageProfilesEmptyText {
            get {
                return ResourceManager.GetString("ConnectionPageProfilesEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact server operator..
        /// </summary>
        public static string ConnectionPageProfilesEmptyWithoutSupportText {
            get {
                return ResourceManager.GetString("ConnectionPageProfilesEmptyWithoutSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact support..
        /// </summary>
        public static string ConnectionPageProfilesEmptyWithSupportText {
            get {
                return ResourceManager.GetString("ConnectionPageProfilesEmptyWithSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profiles.
        /// </summary>
        public static string ConnectionPageProfilesLabel {
            get {
                return ResourceManager.GetString("ConnectionPageProfilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of available profiles is loading.
        ///Please wait....
        /// </summary>
        public static string ConnectionPageProfilesLoadingText {
            get {
                return ResourceManager.GetString("ConnectionPageProfilesLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session is expired.
        /// </summary>
        public static string ConnectionPageSessionExpired {
            get {
                return ResourceManager.GetString("ConnectionPageSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Session.
        /// </summary>
        public static string ConnectionPageSessionRenew {
            get {
                return ResourceManager.GetString("ConnectionPageSessionRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support:.
        /// </summary>
        public static string ConnectionPageSupportContactsLabel {
            get {
                return ResourceManager.GetString("ConnectionPageSupportContactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTR.
        /// </summary>
        public static string FlowDirection {
            get {
                return ResourceManager.GetString("FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Forget.
        /// </summary>
        public static string ForgetLabel {
            get {
                return ResourceManager.GetString("ForgetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string HomePageAddTitle {
            get {
                return ResourceManager.GetString("HomePageAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change Location.
        /// </summary>
        public static string HomePageChangeSecureInternetServerTitle {
            get {
                return ResourceManager.GetString("HomePageChangeSecureInternetServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Servers.
        /// </summary>
        public static string HomePageOwnServerLabel1 {
            get {
                return ResourceManager.GetString("HomePageOwnServerLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string HomePageOwnServerLabel2 {
            get {
                return ResourceManager.GetString("HomePageOwnServerLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Access.
        /// </summary>
        public static string InstituteAccessLabel {
            get {
                return ResourceManager.GetString("InstituteAccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Location.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G}{1}{2}.
        /// </summary>
        public static string NumberToHumanReadable {
            get {
                return ResourceManager.GetString("NumberToHumanReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will take a few seconds....
        /// </summary>
        public static string PleaseWaitPageTitle {
            get {
                return ResourceManager.GetString("PleaseWaitPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Server.
        /// </summary>
        public static string SearchPageInstituteAccessServersLabel {
            get {
                return ResourceManager.GetString("SearchPageInstituteAccessServersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results, please check your search command or try another institute..
        /// </summary>
        public static string SearchPageNoResultsText {
            get {
                return ResourceManager.GetString("SearchPageNoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Organization.
        /// </summary>
        public static string SearchPageOrganizationsLabel {
            get {
                return ResourceManager.GetString("SearchPageOrganizationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add other server.
        /// </summary>
        public static string SearchPageOtherServerTitle {
            get {
                return ResourceManager.GetString("SearchPageOtherServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your own server.
        /// </summary>
        public static string SearchPageOwnServerLabel {
            get {
                return ResourceManager.GetString("SearchPageOwnServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Se_rver.
        /// </summary>
        public static string SearchPageOwnServersLabel {
            get {
                return ResourceManager.GetString("SearchPageOwnServersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for your institute....
        /// </summary>
        public static string SearchPageQueryLabel {
            get {
                return ResourceManager.GetString("SearchPageQueryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your institute.
        /// </summary>
        public static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Internet.
        /// </summary>
        public static string SecureInternetLabel {
            get {
                return ResourceManager.GetString("SecureInternetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_dd server.
        /// </summary>
        public static string SelectOwnServerPageAddServerTitle {
            get {
                return ResourceManager.GetString("SelectOwnServerPageAddServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter server address here.
        /// </summary>
        public static string SelectOwnServerPageHostnameLabel {
            get {
                return ResourceManager.GetString("SelectOwnServerPageHostnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server address.
        /// </summary>
        public static string SelectOwnServerPageTitle {
            get {
                return ResourceManager.GetString("SelectOwnServerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location.
        /// </summary>
        public static string SelectSecureInternetCountryPageTitle {
            get {
                return ResourceManager.GetString("SelectSecureInternetCountryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        public static string SelfUpdateProgressPageTitle {
            get {
                return ResourceManager.GetString("SelfUpdateProgressPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New?.
        /// </summary>
        public static string SelfUpdatePromptPageChangelogTitle {
            get {
                return ResourceManager.GetString("SelfUpdatePromptPageChangelogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer and improved version of the client is available. Stay updated!.
        /// </summary>
        public static string SelfUpdatePromptPageText {
            get {
                return ResourceManager.GetString("SelfUpdatePromptPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string SelfUpdatePromptPageTitle {
            get {
                return ResourceManager.GetString("SelfUpdatePromptPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and _update now
        ///(Client will restart).
        /// </summary>
        public static string SelfUpdatePromptPageUpdateTitle {
            get {
                return ResourceManager.GetString("SelfUpdatePromptPageUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string SessionStatusTypeConnected {
            get {
                return ResourceManager.GetString("SessionStatusTypeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string SessionStatusTypeConnecting {
            get {
                return ResourceManager.GetString("SessionStatusTypeConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string SessionStatusTypeDisconnected {
            get {
                return ResourceManager.GetString("SessionStatusTypeDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting....
        /// </summary>
        public static string SessionStatusTypeDisconnecting {
            get {
                return ResourceManager.GetString("SessionStatusTypeDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string SessionStatusTypeError {
            get {
                return ResourceManager.GetString("SessionStatusTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring....
        /// </summary>
        public static string SessionStatusTypeInitializing {
            get {
                return ResourceManager.GetString("SessionStatusTypeInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing....
        /// </summary>
        public static string SessionStatusTypeTesting {
            get {
                return ResourceManager.GetString("SessionStatusTypeTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string SessionStatusTypeWaiting {
            get {
                return ResourceManager.GetString("SessionStatusTypeWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has detected that your user settings file {1} has become corrupted. This may be due to a crash.
        ///
        ///If you continue, your user settings will be reset to the default..
        /// </summary>
        public static string SettingsCorruptErrorMessage {
            get {
                return ResourceManager.GetString("SettingsCorruptErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt User Settings.
        /// </summary>
        public static string SettingsCorruptErrorTitle {
            get {
                return ResourceManager.GetString("SettingsCorruptErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer _TCP connection.
        /// </summary>
        public static string SettingsPagePreferTCPLabel {
            get {
                return ResourceManager.GetString("SettingsPagePreferTCPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start on sign-on.
        /// </summary>
        public static string SettingsPageStartOnSignon {
            get {
                return ResourceManager.GetString("SettingsPageStartOnSignon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection log.
        /// </summary>
        public static string SettingsPageViewLogButtonLabel {
            get {
                return ResourceManager.GetString("SettingsPageViewLogButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View _log....
        /// </summary>
        public static string SettingsPageViewLogTitle {
            get {
                return ResourceManager.GetString("SettingsPageViewLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires reauthorization..
        /// </summary>
        public static string SystemTrayBalloonAutoReconnectFailedMessage2 {
            get {
                return ResourceManager.GetString("SystemTrayBalloonAutoReconnectFailedMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not reconnect to {0}.
        /// </summary>
        public static string SystemTrayBalloonAutoReconnectFailedTitle {
            get {
                return ResourceManager.GetString("SystemTrayBalloonAutoReconnectFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP={0}, IPv6={1}.
        /// </summary>
        public static string SystemTrayBalloonConnectedMessage {
            get {
                return ResourceManager.GetString("SystemTrayBalloonConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Connected.
        /// </summary>
        public static string SystemTrayBalloonConnectedTitle {
            get {
                return ResourceManager.GetString("SystemTrayBalloonConnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string SystemTrayBalloonDisconnectedMessage {
            get {
                return ResourceManager.GetString("SystemTrayBalloonDisconnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window has been minimized here..
        /// </summary>
        public static string SystemTrayBalloonHiddenMessage {
            get {
                return ResourceManager.GetString("SystemTrayBalloonHiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew before {0}.
        /// </summary>
        public static string SystemTrayBalloonRenewSessionMessage {
            get {
                return ResourceManager.GetString("SystemTrayBalloonRenewSessionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is about to expire.
        /// </summary>
        public static string SystemTrayBalloonRenewSessionTitle {
            get {
                return ResourceManager.GetString("SystemTrayBalloonRenewSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string SystemTrayMenuAbout {
            get {
                return ResourceManager.GetString("SystemTrayMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string SystemTrayMenuExit {
            get {
                return ResourceManager.GetString("SystemTrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string SystemTrayMenuOpen {
            get {
                return ResourceManager.GetString("SystemTrayMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings....
        /// </summary>
        public static string SystemTrayMenuSettings {
            get {
                return ResourceManager.GetString("SystemTrayMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:day|days} and {1:hour|hours}.
        /// </summary>
        public static string TimeSpanDaysAndHours {
            get {
                return ResourceManager.GetString("TimeSpanDaysAndHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:hour|hours} and {1:minute|minutes}.
        /// </summary>
        public static string TimeSpanHoursAndMinutes {
            get {
                return ResourceManager.GetString("TimeSpanHoursAndMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:minute|minutes} and {1:second|seconds}.
        /// </summary>
        public static string TimeSpanMinutesAndSeconds {
            get {
                return ResourceManager.GetString("TimeSpanMinutesAndSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not Available).
        /// </summary>
        public static string TimeSpanNotAvailable {
            get {
                return ResourceManager.GetString("TimeSpanNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:second|seconds}.
        /// </summary>
        public static string TimeSpanSeconds {
            get {
                return ResourceManager.GetString("TimeSpanSeconds", resourceCulture);
            }
        }
    }
}
