//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eduVPN.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eduVPN.Views.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Powered by SURFnet.
        /// </summary>
        public static string AboutPageAppBannerTitle {
            get {
                return ResourceManager.GetString("AboutPageAppBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2017-{0}
        ///The Commons Conservancy eduVPN Programme.
        /// </summary>
        public static string AboutPageCopyright2 {
            get {
                return ResourceManager.GetString("AboutPageCopyright2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutPageVersion {
            get {
                return ResourceManager.GetString("AboutPageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Country.
        /// </summary>
        public static string AuthenticatingCountrySelectPageListLabel {
            get {
                return ResourceManager.GetString("AuthenticatingCountrySelectPageListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Institution.
        /// </summary>
        public static string AuthenticatingInstituteSelectPageListLabel {
            get {
                return ResourceManager.GetString("AuthenticatingInstituteSelectPageListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client needs {0} authorization, and has opened your web browser. The client will continue after you complete the authorization....
        /// </summary>
        public static string AuthorizationPopupMessage2 {
            get {
                return ResourceManager.GetString("AuthorizationPopupMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting For Authorization.
        /// </summary>
        public static string AuthorizationPopupTitle {
            get {
                return ResourceManager.GetString("AuthorizationPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBackTitle {
            get {
                return ResourceManager.GetString("ButtonBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonCloseTitle {
            get {
                return ResourceManager.GetString("ButtonCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connect!.
        /// </summary>
        public static string ButtonConnectTitle {
            get {
                return ResourceManager.GetString("ButtonConnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Error Text.
        /// </summary>
        public static string ButtonCopyErrorTitle {
            get {
                return ResourceManager.GetString("ButtonCopyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dismiss Error.
        /// </summary>
        public static string ButtonDismissErrorTitle {
            get {
                return ResourceManager.GetString("ButtonDismissErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string ButtonOKTitle {
            get {
                return ResourceManager.GetString("ButtonOKTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ButtonSettingsTitle {
            get {
                return ResourceManager.GetString("ButtonSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Provider.
        /// </summary>
        public static string ConnectingInstanceAndProfileSelectPanelInstanceListLabel {
            get {
                return ResourceManager.GetString("ConnectingInstanceAndProfileSelectPanelInstanceListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profile.
        /// </summary>
        public static string ConnectingInstanceAndProfileSelectPanelProfileListLabel {
            get {
                return ResourceManager.GetString("ConnectingInstanceAndProfileSelectPanelProfileListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profile.
        /// </summary>
        public static string ConnectingInstanceProfileSelectPanelInstanceProfileListLabel {
            get {
                return ResourceManager.GetString("ConnectingInstanceProfileSelectPanelInstanceProfileListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Provider.
        /// </summary>
        public static string ConnectingInstanceSelectPanelInstanceListLabel {
            get {
                return ResourceManager.GetString("ConnectingInstanceSelectPanelInstanceListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profile.
        /// </summary>
        public static string ConnectingProfileSelectPanelProfileListLabel {
            get {
                return ResourceManager.GetString("ConnectingProfileSelectPanelProfileListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hostname.
        /// </summary>
        public static string CustomInstancePageHostnameLabel {
            get {
                return ResourceManager.GetString("CustomInstancePageHostnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required OAuth parameter &quot;state&quot; is missing or incorrect..
        /// </summary>
        public static string ErrorOAuthState {
            get {
                return ResourceManager.GetString("ErrorOAuthState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _other address.
        /// </summary>
        public static string InstanceSourcePageCustomButtonTitle {
            get {
                return ResourceManager.GetString("InstanceSourcePageCustomButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to your _Institution.
        /// </summary>
        public static string InstanceSourcePageInstituteAccessButtonTitle2 {
            get {
                return ResourceManager.GetString("InstanceSourcePageInstituteAccessButtonTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Safely use the Internet.
        /// </summary>
        public static string InstanceSourcePageSecureInternetButtonTitle2 {
            get {
                return ResourceManager.GetString("InstanceSourcePageSecureInternetButtonTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        public static string ListBoxNoItems {
            get {
                return ResourceManager.GetString("ListBoxNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string ListBoxNull {
            get {
                return ResourceManager.GetString("ListBoxNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string MessageMaintenanceBegin {
            get {
                return ResourceManager.GetString("MessageMaintenanceBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string MessageMaintenanceEnd {
            get {
                return ResourceManager.GetString("MessageMaintenanceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Notification.
        /// </summary>
        public static string MessageMaintenanceTitle {
            get {
                return ResourceManager.GetString("MessageMaintenanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string MessageNotificationTitle {
            get {
                return ResourceManager.GetString("MessageNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:G}{1}{2}.
        /// </summary>
        public static string NumberToHumanReadable {
            get {
                return ResourceManager.GetString("NumberToHumanReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password for &quot;{0}&quot;:.
        /// </summary>
        public static string PasswordPopupMessage {
            get {
                return ResourceManager.GetString("PasswordPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Password.
        /// </summary>
        public static string PasswordPopupPasswordLabel {
            get {
                return ResourceManager.GetString("PasswordPopupPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPopupTitle {
            get {
                return ResourceManager.GetString("PasswordPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _another.
        /// </summary>
        public static string RecentConfigurationSelectPageAddButtonTitle {
            get {
                return ResourceManager.GetString("RecentConfigurationSelectPageAddButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added VPN Profiles.
        /// </summary>
        public static string RecentConfigurationSelectPageConnectionListTitle {
            get {
                return ResourceManager.GetString("RecentConfigurationSelectPageConnectionListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask me _later.
        /// </summary>
        public static string SelfUpdatePopupAskLaterButtonTitle {
            get {
                return ResourceManager.GetString("SelfUpdatePopupAskLaterButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s _New?.
        /// </summary>
        public static string SelfUpdatePopupChangelogButtonTitle {
            get {
                return ResourceManager.GetString("SelfUpdatePopupChangelogButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer and improved version of the client is available. Stay updated!.
        /// </summary>
        public static string SelfUpdatePopupMessage3 {
            get {
                return ResourceManager.GetString("SelfUpdatePopupMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this _version.
        /// </summary>
        public static string SelfUpdatePopupSkipButtonTitle {
            get {
                return ResourceManager.GetString("SelfUpdatePopupSkipButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string SelfUpdatePopupTitle {
            get {
                return ResourceManager.GetString("SelfUpdatePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and _update now
        ///(Client will restart).
        /// </summary>
        public static string SelfUpdatePopupUpdateButtonTitle {
            get {
                return ResourceManager.GetString("SelfUpdatePopupUpdateButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has detected that your user settings file {1} has become corrupted. This may be due to a crash.
        ///
        ///If you continue, your user settings will be reset to the default..
        /// </summary>
        public static string SettingsCorruptErrorMessage {
            get {
                return ResourceManager.GetString("SettingsCorruptErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt User Settings.
        /// </summary>
        public static string SettingsCorruptErrorTitle {
            get {
                return ResourceManager.GetString("SettingsCorruptErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Do not enable this when roaming in public untrusted networks..
        /// </summary>
        public static string SettingsPageAllowLocalDescription {
            get {
                return ResourceManager.GetString("SettingsPageAllowLocalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow _Local Traffic.
        /// </summary>
        public static string SettingsPageAllowLocalLabel {
            get {
                return ResourceManager.GetString("SettingsPageAllowLocalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the client cannot connect, or can connect but doesn&apos;t transfer data, connecting over TCP could solve this..
        /// </summary>
        public static string SettingsPageForceTCPDescription2 {
            get {
                return ResourceManager.GetString("SettingsPageForceTCPDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Over _TCP.
        /// </summary>
        public static string SettingsPageForceTCPLabel {
            get {
                return ResourceManager.GetString("SettingsPageForceTCPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you need multiple simultaneous OpenVPN connections, select the TAP interface for the client below..
        /// </summary>
        public static string SettingsPageInterfaceDescription2 {
            get {
                return ResourceManager.GetString("SettingsPageInterfaceDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TAP _Interface.
        /// </summary>
        public static string SettingsPageInterfaceLabel {
            get {
                return ResourceManager.GetString("SettingsPageInterfaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Disconnect.
        /// </summary>
        public static string StatusPageDisconnectButtonTitle {
            get {
                return ResourceManager.GetString("StatusPageDisconnectButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string StatusPageInstance {
            get {
                return ResourceManager.GetString("StatusPageInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Messages.
        /// </summary>
        public static string StatusPageMessagesLabel {
            get {
                return ResourceManager.GetString("StatusPageMessagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string StatusPageProfile {
            get {
                return ResourceManager.GetString("StatusPageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes In.
        /// </summary>
        public static string StatusPageSessionInfoBytesIn {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoBytesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes Out.
        /// </summary>
        public static string StatusPageSessionInfoBytesOut {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoBytesOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string StatusPageSessionInfoDuration {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4.
        /// </summary>
        public static string StatusPageSessionInfoIPv4 {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoIPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6.
        /// </summary>
        public static string StatusPageSessionInfoIPv6 {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoIPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Info.
        /// </summary>
        public static string StatusPageSessionInfoTitle {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View _log.
        /// </summary>
        public static string StatusPageSessionInfoViewLogButtonTitle {
            get {
                return ResourceManager.GetString("StatusPageSessionInfoViewLogButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusPageStatus {
            get {
                return ResourceManager.GetString("StatusPageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP={0}, IPv6={1}.
        /// </summary>
        public static string SystemTrayBalloonConnectedMessage {
            get {
                return ResourceManager.GetString("SystemTrayBalloonConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Connected.
        /// </summary>
        public static string SystemTrayBalloonConnectedTitle {
            get {
                return ResourceManager.GetString("SystemTrayBalloonConnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string SystemTrayBalloonDisconnectedMessage {
            get {
                return ResourceManager.GetString("SystemTrayBalloonDisconnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window has been minimized here..
        /// </summary>
        public static string SystemTrayBalloonHiddenMessage {
            get {
                return ResourceManager.GetString("SystemTrayBalloonHiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string SystemTrayMenuAbout {
            get {
                return ResourceManager.GetString("SystemTrayMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string SystemTrayMenuExit {
            get {
                return ResourceManager.GetString("SystemTrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string SystemTrayMenuOpen {
            get {
                return ResourceManager.GetString("SystemTrayMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings....
        /// </summary>
        public static string SystemTrayMenuSettings {
            get {
                return ResourceManager.GetString("SystemTrayMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection _info....
        /// </summary>
        public static string SystemTrayMenuStatus {
            get {
                return ResourceManager.GetString("SystemTrayMenuStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h\:mm\:ss.
        /// </summary>
        public static string TimeSpanInSeconds {
            get {
                return ResourceManager.GetString("TimeSpanInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d\.hh\:mm\:ss.
        /// </summary>
        public static string TimeSpanInSecondsWithDays {
            get {
                return ResourceManager.GetString("TimeSpanInSecondsWithDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not reuse the TOTP. Wait until a fresh TOTP is generated..
        /// </summary>
        public static string TOTPAuthenticationPanelNote {
            get {
                return ResourceManager.GetString("TOTPAuthenticationPanelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Response.
        /// </summary>
        public static string TOTPAuthenticationPanelResponseLabel {
            get {
                return ResourceManager.GetString("TOTPAuthenticationPanelResponseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your two-factor method and enter the security code:.
        /// </summary>
        public static string TwoFactorAuthenticationPopupMessage {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Method.
        /// </summary>
        public static string TwoFactorAuthenticationPopupMethodLabel {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationPopupMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor Authentication.
        /// </summary>
        public static string TwoFactorAuthenticationPopupTitle {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires two-factor authentication.
        /// </summary>
        public static string TwoFactorAuthenticationRequired {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and password for &quot;{0}&quot;:.
        /// </summary>
        public static string UsernamePasswordPopupMessage {
            get {
                return ResourceManager.GetString("UsernamePasswordPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Password.
        /// </summary>
        public static string UsernamePasswordPopupPasswordLabel {
            get {
                return ResourceManager.GetString("UsernamePasswordPopupPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string UsernamePasswordPopupTitle {
            get {
                return ResourceManager.GetString("UsernamePasswordPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Username.
        /// </summary>
        public static string UsernamePasswordPopupUsernameLabel {
            get {
                return ResourceManager.GetString("UsernamePasswordPopupUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Response.
        /// </summary>
        public static string YubiKeyAuthenticationPanelResponseLabel {
            get {
                return ResourceManager.GetString("YubiKeyAuthenticationPanelResponseLabel", resourceCulture);
            }
        }
    }
}
